name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint flake8 bandit coverage pytest pytest-cov mutmut

      - name: Download NLTK data stopwords
        run: |
          python -m nltk.downloader stopwords

      - name: Lint code
        run: |
          pylint src/
          flake8 src/
          bandit -r src/

      - name: Run tests and collect coverage
        run: |
          coverage run -m pytest tests/
          coverage report > coverage.txt

      - name: Commit updated coverage.txt
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add coverage.txt
          git commit -m "Update coverage.txt" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show coverage.txt in workflow log
        run: cat coverage.txt

      
      - name: Update coverage report in README
        run: |
          python update_covarage.py

      - name: Diff README before commit
        run: |
          git diff README.md || echo "No diff"
          
      - name: Commit and push any changes made by coverage.py
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
