name: Publish Trained Model

# only trigger on tags, ‘verify‘ has already been triggered by push to PR
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload model to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./c2_Classifier_Sentiment_Model
            ./c1_BoW_Sentiment_Model.pkl
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}